### ISSUE TITLE
Running in Dev Container returns an error that no manifest can be found

### ISSUE THREAD

**Issue by michaelklopf** [microsoft/generative-ai-for-beginners#187] opened 2023-11-17 15:08 UTC
**Describe the bug**
Running project in dev container returns error. 

```
Error fetching image details: No manifest found for mcr.microsoft.com/devcontainers/universal:2.
```

**To Reproduce**
Cloning the repository, opening the folder with VSCode on macOS and letting the DevContainer build returns the error

**Expected behavior**
Run of DevContainer should be successful

**Desktop (please complete the following information):**
 - OS: macOS 13.5.2
 - Docker Desktop 4.21.1
- VSCode 1.84.2

**Additional context**
I have basic experience with Docker, so this could be a user error, but I'm not sure.

**Comment by nitya** [comment] 2023-11-21 05:57
Hi @michaelklopf - thanks for the report.

I tried to replicate this:
 - OS: macOS 12.7.1 (Monterey)
 - Docker Desktop: 4.25.1
 - VS Code: 1.85.0-insider

I was unable to reproduce the issue and get the same error message on my device. 
Looking at the error message itself, that indicates that one of two things is possible:
 - You cannot access the Microsoft Container Registry (mcr) where the image is located
 - You can access it but it does not contain the image for the tag (universal:2)
 
I just checked the [Microsoft Artifact Registry tags here](https://mcr.microsoft.com/en-us/product/devcontainers/universal/tags) - and you can see that the "2" tag exists annd has the specific image string provided. **So I have to assume that can't be the issue.**

Which leaves the possibility that for some reason your local device was not able to access the registry at the given time. Were you able to check if you were online at the time? (If you see the issue again, try visiting that link to the Artifact above in browser to verify you can. see it)

**Can you check if the issue persists** or did you get that only on occasion?

**Comment by michaelklopf** [comment] 2023-11-21 11:21
@nitya I tried with the `docker pull` command directly and get the error

```
2: Pulling from devcontainers/universal
no matching manifest for linux/arm64/v8 in the manifest list entries
```

I guess that being on an ARM Mac it needs to be a linux arm64 compatible version, are you running it on an Intel or ARM Mac?

**Comment by potateros** [comment] 2023-11-21 18:38
I am also facing this same issue while trying to use Dev Container in VSCode. My error message is
```
[5591 ms] Looking up Docker credential helper for 'mcr.microsoft.com'.
2: Pulling from devcontainers/universal
no matching manifest for linux/arm64/v8 in the manifest list entries
[6498 ms] []
[6498 ms] Error: No such image: mcr.microsoft.com/devcontainers/universal:2
```

I then tried running `docker pull mcr.microsoft.com/devcontainers/universal:2` in terminal, and my error message is 
```
2: Pulling from devcontainers/universal
no matching manifest for linux/arm64/v8 in the manifest list entries
```

I am able to find it in the Microsoft Artifact Registry. Looking at the error, it seems like there is no image available for arm64 devices. @nitya are you using an Apple Silicon device? That may be the reason. Until Microsoft adds arm64, we won't be able to use Dev Containers.

CPU: M1 Pro
OS: macOS 14.0
Docker Desktop: 4.25.0 (126437)
VSCode: 1.84.2 (Universal)

**Comment by nityadev** [comment] 2023-11-22 03:01
(This is @Nitya) 

@michaelklopf - ah it is an ARM issue. You're right - I am still on an Intel Mac so I didn't get that issue.
@potateros  - thanks for the suggestion!! @michaelklopf  - can you try the suggestion above as a temporary fix and let me know if that worked for you?

In the meantime, some context if useful:
The [Dev Container Images By Microsoft ](https://hub.docker.com/_/microsoft-devcontainers?tab=description) on Docker Hub indicates that there are limitations for support of ARM64 images. Specifically, the we would need to use an image with a 'buster' or 'bullseye' tag. Currently the 'universal:2' does not support it - _but the [Python base image does](https://mcr.microsoft.com/en-us/product/devcontainers/python/tags)_ - so it might be possible to reconfigure the container with that base image and see if that works.

I can try that out (or if you do so let me know how it goes).

**Comment by PAN740623** [comment] 2023-11-23 00:48
报告错误

**Comment by michaelklopf** [comment] 2023-11-24 08:02
@potateros Yeah, I'm on an ARM Mac. Thank you for the hint

@nitya It did work and the dev container is building and running now

**Comment by koreyspace** [comment] 2023-11-24 18:12
Glad to see this is working @michaelklopf , thanks for the help @nitya . Closing this.

**Closed by koreyspace** 2023-11-24 18:12 UTC
Labels: needs-review
